[default]
extend-ignore-identifiers-re = [
    "[a-f0-9]{7,}", 
    "[Ff][Oo][Oo]",
    "[a-zA-Z0-9]{20,}",
]

[files]
extend-exclude = [
    "**/CHANGELOG.md",
    "**/tests/fixtures/**",
    "gix-config/benches/large_config_file.rs",
    "gix-glob/tests/wildmatch/mod.rs"
]


[default.extend-words]
rela = "rela"
unter = "unter"
