[package]
name = "gix-revwalk"
version = "0.9.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate providing utilities for walking the revision graph"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.13.1", path = "../gix-hash" }
gix-object = { version = "^0.38.0", path = "../gix-object" }
gix-date = { version = "^0.8.0", path = "../gix-date" }
gix-hashtable = { version = "^0.4.0", path = "../gix-hashtable" }
gix-commitgraph = { version = "^0.22.0", path = "../gix-commitgraph" }

thiserror = "1.0.26"
smallvec = "1.10.0"
